name: Node.js Package

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci

      - name: Get previous version from main
        id: prev_version
        run: |
          git fetch origin main --depth=1
          PREV_VERSION=$(git show origin/main:package.json | grep '"version":' | head -1 | sed -E 's/.*"([^"]+)".*/\1/')
          echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_ENV

      - name: Get current version
        id: curr_version
        run: |
          CURR_VERSION=$(grep '"version":' package.json | head -1 | sed -E 's/.*"([^"]+)".*/\1/')
          echo "CURR_VERSION=$CURR_VERSION" >> $GITHUB_ENV

      - name: Check version change
        run: |
          echo "Previous version: $PREV_VERSION"
          echo "Current version: $CURR_VERSION"
          if [ "$PREV_VERSION" = "$CURR_VERSION" ]; then
            echo "Version not changed. Skipping publish."
            exit 0
          fi

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
